# Indexing and Selection
Perform selection and operation on the slice

#### Basic Selection

In [1]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[1]
# pick the value of index 1

1

In [3]:
arr[2:5]
# pick the value from index 2 to 5 (exclusive)

array([2, 3, 4])

In [4]:
arr[:3]
# zero to 3 (exclusive)

array([0, 1, 2])

In [5]:
arr[5:]
# 5 to infinity

array([ 5,  6,  7,  8,  9, 10])

In [6]:
arr[5:-1]
# 5 to end (exclusive)

array([5, 6, 7, 8, 9])

#### Array Selection + Broadcast Operation
You can perform a 'broadcast' operation on array selections like this:

In [7]:
arr[0:3] = 9

In [8]:
arr

array([ 9,  9,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
my_slice = arr[0:4]
my_slice[1:] = 2
my_slice

array([9, 2, 2, 2])

Broadcast operations will alter the contents of the selected elements as well as the original array on which the slice was selected...YES. Its a shallow copy.

In [10]:
arr

array([ 9,  2,  2,  2,  4,  5,  6,  7,  8,  9, 10])

This is done to conserve memory when duplicating large datasets, if you really want a copy, you must explicitely say so using the ```copy()``` method

In [11]:
my_copy_slice = arr[:].copy()

In [12]:
my_copy_slice[:] = 10

In [13]:
my_copy_slice

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [14]:
arr #was not altered

array([ 9,  2,  2,  2,  4,  5,  6,  7,  8,  9, 10])

#### Accessing Matrices
Assuming we have a 4x3 array:

In [15]:
my_mat = np.array([[0,1,2,3], [10,11,12,13], [20,21,22,23]])
my_mat

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

to select the value of '12' we can either (1) pick apart the array or use the (2) comma notation

In [16]:
my_mat[1][2]

12

In [17]:
my_mat[1,2]

12

to select a range of values, example: [1,2] and [11,12]:

In [18]:
my_mat[0:2,1:3]

array([[ 1,  2],
       [11, 12]])