# Indexing and Selection

In [1]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[1]
# pick the value of index 1

1

In [3]:
arr[2:5]
# pick the value from index 2 to 5 (exclusive)

array([2, 3, 4])

In [4]:
arr[:3]
# zero to 3 (exclusive)

array([0, 1, 2])

In [5]:
arr[5:]
# 5 to infinity

array([ 5,  6,  7,  8,  9, 10])

In [6]:
arr[5:-1]
# 5 to end (exclusive)

array([5, 6, 7, 8, 9])