# Operations
You can perform broadcast operations on arrays

In [1]:
import numpy as np
np.random.seed(100)

In [2]:
my_array = np.arange(0,11)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Arithmetic Functions

In [3]:
my_array * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [4]:
my_array + my_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Notes on errors: Array operations continue no matter what, Numpy only logs a warning.

In [5]:
100 / my_array

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([         inf, 100.        ,  50.        ,  33.33333333,
        25.        ,  20.        ,  16.66666667,  14.28571429,
        12.5       ,  11.11111111,  10.        ])

#### Universal Functions
[Reference](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [6]:
my_array.min()
# min value
# or
np.min(my_array)

0

In [7]:
np.sin(my_array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [8]:
np.log(my_array)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])